# Generated by Django 5.2.5 on 2025-08-11 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarouselSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(max_length=300)),
                ('image', models.ImageField(help_text='Imagen del carrusel', upload_to='carousel/')),
                ('link_text', models.CharField(blank=True, help_text='#', max_length=50)),
                ('link_url', models.URLField(blank=True, help_text='URL Del boton')),
                ('order', models.IntegerField(default=0, help_text='Orden de aparición')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Carrusel',
                'verbose_name_plural': 'Diapositivas del carrusel',
                'ordering': ['order'],
            },
        ),
    ]
